name: HSRGearboxResidualPlacePPO

params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: True # flag which sets whether to load the checkpoint
  load_path: runs/HSRGearboxResidualPlace/nn/HSRGearboxResidualPlace.pth # path to the checkpoint to load

  config:
    name: HSRGearboxResidualPlace
    full_experiment_name: HSRGearboxResidualPlace
    env_name: rlgpu
    device: cuda
    device_name: cuda
    multi_gpu: False
    ppo: True
    mixed_precision: False
    clip_actions: False
    normalize_input: True
    normalize_value: True
    normalize_advantage: True
    num_actors: 1
    num_actions: 8
    num_observations: 19
    action_scale: 0.2
    reward_shaper:
      scale_value: 0.1
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 256
    save_best_after: 50
    save_frequency: 100
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 256
    minibatch_size: 8192
    mini_epochs: 8
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
